name: Publish NPM Version Info

on:
  workflow_dispatch:
  release:
    types: [published]

concurrency:
  group: publish-version-info-${{ github.event.release.tag_name || github.run_id }}
  cancel-in-progress: false

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT }}
          repository: lyswhut/lx-music-mobile-version-info
          event-type: npm-release
